version: '3.8'

services:
  auth:
    container_name: auth-service
    image: 090188239653.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
    volumes:
      - /home/ubuntu/config/auth/application.yml:/config/auth/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/auth/application.yml
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true